apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: demo
  name: demo
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: demo
  name: demo
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: demo:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-java11:latest
    type: Source
  successfulBuildsHistoryLimit: 5
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: demo
  name: demo
spec:
  replicas: 5
  selector:
    app: demo
    deployment-config.name: demo
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: demo
        deployment-config.name: demo
        prometheus/job_name: spring-boot
    spec:
      containers:
      - image: 172.30.1.1:5000/myproject/demo
        imagePullPolicy: Always
        name: demo
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - demo
      from:
        kind: ImageStreamTag
        name: demo:latest
    type: ImageChange
