apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
        - targets: []
        scheme: http
        timeout: 10s
        api_version: v1
    scrape_configs:
    - job_name: prometheus
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - localhost:9090
    - job_name: spring-boot
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /actuator/prometheus
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - myproject
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_prometheus_job_name, __meta_kubernetes_pod_container_port_number]
        separator: ':'
        regex: spring-boot:8080
        action: keep
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: app
      - source_labels: [__meta_kubernetes_pod_phase]
        target_label: phase
